# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_blog_album_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='album_logo',
            new_name='blog_image',
        ),
    ]
