# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20171026_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
